agent: support max_tokens, temperature and memory_size options
homanp/superagent pull request #182
Opened 2023-07-13 16:15 UTC by bdqfork

## Summary

Add max_tokens, temperature and memory_size options to agent. I did not add this as predict params because it required user always feed to run agent. I think it should be a property of agent more properly, so added in agent creation api.

Fixes

Depends on

## Test plan

-

## Screenshots

## Checklist

- [x] My code follows the code style of this project and passes `make format`.
- [x] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

2023-07-13 16:16 UTC, bdqfork commented
for #72

2023-07-13 17:45 UTC, homanp requested changes
Thanks for this submission @bdqfork!

I have some comments in the PR and a general comment:

The `memorySize`, `maxTokens` and `temperature` should be passed in the existing `llm` dictionary which handles the other llm specific settings such as `model`. 
This way of implementing also means that we don't need to add any fields to the DB and you changes there should not be necessary.

2023-07-13 17:45 UTC, homanp commented on app/api/agents.py
> +                result = agent_executor(input)
@bdqfork Why is this changed? This will break invocation. Please revert to using `agent_base.process_payload`

2023-07-14 02:10 UTC, bdqfork commented on app/api/agents.py
> +                result = agent_executor(input)
I'm sorry. I forgot to explain. When run agent in ui, I noticed `agent_base.process_payload` will encode `input` to json string, then feed into prompt. For example,  a prompt template like below:
```
User: {input}
```

2023-07-14 02:24 UTC, bdqfork commented
> Thanks for this submission @bdqfork!
> 
> I have some comments in the PR and a general comment:
> 
> The `memorySize`, `maxTokens` and `temperature` should be passed in the existing `llm` dictionary which handles the other llm specific settings such as `model`. This way of implementing also means that we don't need to add any fields to the DB and you changes there should not be necessary.

Oh, it's indeed a better solution. Thank you for reminding me.

2023-07-14 03:30 UTC, homanp commented
> > Thanks for this submission @bdqfork!
> 
> > 
> 
> > I have some comments in the PR and a general comment:
> 
> > 
> 
> > The `memorySize`, `maxTokens` and `temperature` should be passed in the existing `llm` dictionary which handles the other llm specific settings such as `model`. This way of implementing also means that we don't need to add any fields to the DB and you changes there should not be necessary.
> 
> 
> 
> Oh, it's indeed a better solution. Thank you for reminding me.

Ping when you are ready!

2023-07-15 17:58 UTC, bdqfork commented
Already updated! @homanp

2023-07-15 18:08 UTC, homanp commented
> Already updated! @homanp 

Thank you!

2023-07-16 12:50 UTC, homanp commented
> Already updated! @homanp 

Please revert to using procees_payload as well!

2023-07-16 15:02 UTC, bdqfork commented on app/api/agents.py
> +                result = agent_executor(input)
@homanp I reverted, but I think the input params may be wrong in agent run . The final input to prompt is a json string.

2023-07-16 15:15 UTC, homanp approved these changes

2023-07-16 15:15 UTC, homanp commented on app/api/agents.py
> +                "memorySize": body.memorySize,
`memorySize`, `maxTokens` and `temperature` should be passed in the `llm` dictionary. So this line won't be needed.

2023-07-16 15:15 UTC, homanp commented on app/api/agents.py
> +                "maxTokens": body.maxTokens,
`memorySize`, `maxTokens` and `temperature` should be passed in the `llm` dictionary. So this line won't be needed.

2023-07-16 15:15 UTC, homanp commented on app/api/agents.py
> +                "temperature": body.temperature,
`memorySize`, `maxTokens` and `temperature` should be passed in the `llm` dictionary. So this line won't be needed.

2023-07-16 15:15 UTC, homanp commented on app/api/agents.py
> +            result = agent_executor(input)
@bdqfork Why is this changed? This will break invocation. Please revert to using agent_base.process_payload

2023-07-16 15:15 UTC, homanp commented on app/lib/agents/base.py
> +        self.memory_size = agent.memorySize
this key value should be present in `self.llm`.

2023-07-16 15:15 UTC, homanp commented on app/lib/agents/base.py
> +        self.max_tokens = agent.maxTokens
this key value should be present in `self.llm`.

2023-07-16 15:15 UTC, homanp commented on app/lib/agents/base.py
> +        self.temperature = agent.temperature
this key value should be present in `self.llm`.

2023-07-16 15:15 UTC, homanp commented on app/lib/agents/base.py
> +                )
What does this do?

2023-07-16 15:15 UTC, homanp commented on app/lib/models/agent.py
> +    memorySize: int = 3
Not need if you use the `llm` dict.

2023-07-16 15:15 UTC, homanp commented on app/lib/models/agent.py
> +    maxTokens: int = 1024
Not need if you use the `llm` dict.

2023-07-16 15:15 UTC, homanp commented on app/lib/models/agent.py
> +    temperature: float = 0
Not need if you use the `llm` dict.

2023-07-16 15:15 UTC, homanp commented on prisma/migrations/20230713153726_/migration.sql
> +ADD COLUMN     "temperature" DOUBLE PRECISION NOT NULL DEFAULT 0;
You can remove this migration

2023-07-16 15:15 UTC, homanp commented on prisma/schema.prisma
> +  temperature   Float           @default(0)
Not necessary if you you the `llm` dict

2023-07-16 15:15 UTC, homanp commented on prisma/schema.prisma
> +  maxTokens     Int             @default(1024)
Not necessary if you you the `llm` dict

2023-07-16 15:15 UTC, homanp commented on prisma/schema.prisma
> +  memorySize    Int             @default(3)
Not necessary if you you the `llm` dict

2023-07-16 15:15 UTC, homanp commented on app/api/agents.py
> +                result = agent_executor(input)
Please revert this to previous. It unifies the different input types

2023-07-16 15:15 UTC, homanp commented on app/api/agents.py
> +                result = agent_executor(input)
Please revert back to using process_payload

2023-07-16 15:15 UTC, homanp commented on app/api/agents.py
> +            result = agent_executor(input)
Please revert back to usin process_payload

2023-07-16 15:15 UTC, homanp commented on app/api/agents.py
> +                result = agent_executor(input)
Yeah, should it should be

2023-07-17 12:07 UTC, bdqfork commented
Is there anything else to update?

2023-07-17 12:35 UTC, homanp commented
> Is there anything else to update?

No thank you! Just testing and then deploying!

2023-07-18 12:37 UTC, homanp commented
@bdqfork did you test this on your end?

2023-07-18 12:38 UTC, bdqfork commented
I did, is something wrong?发自我的 iPhone在 2023年7月18日，20:37，Ismail Pelaseyed ***@***.***> 写道：﻿
@bdqfork did you test this on your end?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-07-18 13:14 UTC, homanp commented
@bdqfork did you test the memory changes and new prompt template setup as well?! I didn’t so just want to make sure it will work.

2023-07-18 13:28 UTC, homanp commented
> > 
> 
> I did test in my end. However, we do not have a complete regression testing process. If you are also uncertain, I suggest delaying the merge and waiting for the complete testing action to be filled and passed.
> 
> 

Yes ok, I will run a full test and merge after that!

2023-07-18 13:34 UTC, bdqfork commented on app/lib/agents/base.py
> +                )
In Langchain, the chat model uses different prompt construction methods to differentiate messages from different roles. Please refer to [https://python.langchain.com/docs/modules/model_io/models/chat/how_to/prompts ↗](https://python.langchain.com/docs/modules/model_io/models/chat/how_to/prompts) for more information.

My apologies for the trouble caused. I will submit separate feature requests in the future. Or should I roll back this portion of the code now?

2023-07-18 13:34 UTC, bdqfork commented on app/lib/agents/base.py
> +                )
@homanp

2023-07-18 13:41 UTC, homanp commented on app/lib/agents/base.py
> +                )
If you could roll back and add this is a seperate PR that would make testing easier.

2023-07-18 13:41 UTC, homanp commented on app/lib/agents/base.py
> +                )
If you could roll back and add this is a seperate PR that would make testing easier.

2023-07-18 13:43 UTC, bdqfork commented
I will close this pull request. There is some irrelevant code logic included in it, and I will remove it and resubmit a new pull request.

2023-07-18 13:48 UTC, closed without merging

2023-07-18 14:39 UTC, homanp commented
> I will close this pull request. There is some irrelevant code logic included in it, and I will remove it and resubmit a new pull request.

Appreciate the effort @bdqfork