feat: added sso icons, providers
homanp/superagent pull request #194
Opened 2023-07-17 16:34 UTC by ankushbhardwxj

## Summary

Fixes

#190 

Depends on

## Test plan

-

## Screenshots

## Checklist

- [ ] My code follows the code style of this project and passes `make format`.
- [ ] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

2023-07-17 16:36 UTC, ankushbhardwxj commented on ui/lib/next-auth.js
> +    }),
@homanp : Require these client ids & secrets for the providers.

2023-07-17 16:37 UTC, ankushbhardwxj commented on ui/lib/next-auth.js
> +    }),
I believe AzureADProvider is same as Microsoft Provider. NextAuth doesn't have specifically by the name of Microsoft.

2023-07-17 17:58 UTC, homanp commented on ui/lib/next-auth.js
> +    }),
Correct!

2023-07-17 17:59 UTC, homanp commented on ui/lib/next-auth.js
> +    }),
Please ping when you are ready with this PR.

2023-07-18 22:00 UTC, homanp commented on ui/lib/next-auth.js
> +    }),
@ankushbhardwxj do you need any help with this? If so, ping.

2023-07-19 05:16 UTC, ankushbhardwxj commented on ui/lib/next-auth.js
> +    }),
Didn't get time to get to it yesterday. Will try to wrap this up today. Will ping, if help needed.

2023-07-21 15:55 UTC, ankushbhardwxj commented
@homanp : I guess this PR is ready for a review. 

Two questions:
- Am I supposed to push my `yarn.lock` file or db migration files ?
- Didn't implement Refresh Token flow as of now. Do we want to support that ? I guess only Google & Microsoft have refresh token flow.

Do let me know for any changes 👍🏻

2023-07-21 16:04 UTC, homanp commented
> @homanp : I guess this PR is ready for a review.
> 
> Two questions:
> 
> * Am I supposed to push my `yarn.lock` file, db migration files and `.env` files ?
> * Didn't implement Refresh Token flow as of now. Do we want to support that ? I guess only Google & Microsoft have refresh token flow.
> 
> Do let me know for any changes 👍🏻

Hey, from a glance this looks really good. 
1. You should add your migration files. 
2. No need to add `.env` or `yarn.lock`. 
3. Regarding the refresh token, what happens if we don’t implement, the user gets logged out?

Also did you have the chance to test signup/login with your changes? Everything works?

2023-07-21 17:20 UTC, ankushbhardwxj commented
> Also did you have the chance to test signup/login with your changes? Everything works?

Yes, sign up and login works fine. 

> Regarding the refresh token, what happens if we don’t implement, the user gets logged out?

Yes, the user will require to log in again. Frequency of that depends on expiration duration of the provider we are working with. 

Haven't implemented the authentication middleware yet on the backend. Basically, that's where I'm planning to refresh user tokens. We can also refresh the token on next-auth side. Do let me know which flow seems suitable to you.

2023-07-23 07:24 UTC, homanp commented
> > Also did you have the chance to test signup/login with your changes? Everything works?
> 
> Yes, sign up and login works fine.
> 
> > Regarding the refresh token, what happens if we don’t implement, the user gets logged out?
> 
> Yes, the user will require to log in again. Frequency of that depends on expiration duration of the provider we are working with.
> 
> Haven't implemented the authentication middleware yet on the backend. Basically, that's where I'm planning to refresh user tokens. We can also refresh the token on next-auth side. Do let me know which flow seems suitable to you.

@ankushbhardwxj we can leave it as is. Could we make the different OAuth options optional? This would make it easier for people fork. Could you add that in as well?

2023-07-23 07:33 UTC, ankushbhardwxj commented
> Could we make the different OAuth options optional?

I think they are already optional. If somebody doesn't want to use SSO, they can use the login form.

2023-07-23 09:20 UTC, homanp requested changes
@ankushbhardwxj I noticed two issues when testing: 

1) Regular credentials stopped working (this is fixed now by me)
2) Can't create any objects due to the authorization token missing in all requests.

Can you please fix point 2.

2023-07-24 16:32 UTC, ankushbhardwxj commented on prisma/schema.prisma
> +  url               = env("DATABASE_MIGRATION_URL")
@homanp : Is this the intended naming for the url ?

2023-07-24 16:48 UTC, ankushbhardwxj commented
On testing, found another issue - If OAuth was done to log in first, user cannot sign up using credentials. User should be able to use both flows.

2023-07-24 19:23 UTC, homanp commented
> On testing, found another issue - If OAuth was done to log in first, user cannot sign up using credentials. User should be able to use both flows. 

Could you fix?

2023-07-24 19:24 UTC, ankushbhardwxj commented
I'm onto it, shall push in some time

2023-07-24 19:25 UTC, homanp commented
> I'm onto it, shall push in some time. Also, fixing 2 from above

Isn't the user signed up when using oauth the first time? Why would they need to signup again?

2023-07-24 19:27 UTC, ankushbhardwxj commented
> Isn't the user signed up when using oauth the first time? Why would they need to signup again?

I have found instances, when users although they signed up using Credentials the first time, tried to use log in with OAuth later and vice versa. 
However, it's not super important to support it, we can drop it if required.

2023-07-24 19:28 UTC, homanp commented
> > Isn't the user signed up when using oauth the first time? Why would they need to signup again?
> 
> 
> 
> I have found instances, when users although they signed up using Credentials the first time, tried to use log in with OAuth later and vice versa. 
> 
> However, it's not super important to support it, we can drop it if required. 

Yeah, think we can leave it for later

2023-07-24 22:32 UTC, homanp requested changes

2023-07-24 22:32 UTC, homanp commented on app/api/agents.py
> +    is_oauth_token = False
You are repeating this in every api endpoint. this is not necessary. Instead you should use the lib/auth/prisma to handle this globally for every endpoint. 

Also I tested and I get 403 when trying to create objects still.  

Would you mind abstracting this into one place in the code so that we keep it DRY?

2023-07-26 08:44 UTC, homanp commented on app/api/agents.py
> +    is_oauth_token = False
@ankushbhardwxj did you have the time look at my comments?

2023-07-26 18:52 UTC, ankushbhardwxj commented on app/api/agents.py
> +    is_oauth_token = False
@homanp : yeah I did check this out, didn't get time to get to it, will push the changes soon.

2023-07-29 17:43 UTC, homanp reviewed
Hi @ankushbhardwxj did you test your implementation with listing/creating objects both for OAuth and email/password users?!

2023-07-29 17:44 UTC, ankushbhardwxj commented
@homanp : yes, I am able to create and list agents, tools, prompts, documents, etc. Which object were you not able to create when you tested earlier ? Did I miss out anything ?

2023-07-29 18:12 UTC, ankushbhardwxj commented
@homanp : I guess this PR is ready for another review. Do let me know for changes.

2023-07-30 17:33 UTC, homanp commented
> @homanp : I guess this PR is ready for another review. Do let me know for changes. 

Thanks! Will test and merge. This PR is next ip! 😻

2023-07-31 19:17 UTC, homanp requested changes
I can't login using regular auth with email password.

2023-07-31 19:25 UTC, ankushbhardwxj commented
@homanp sure, will take a look at it. Few questions just to clarify,
- Is this a fresh user ? Did you do normal sign up and then do the log in ?
- Did you do login with OAuth and then try to login using normal email and password ?

2023-07-31 20:23 UTC, homanp commented
> @homanp sure, will take a look at it. Few questions just to clarify,
> 
> * Is this a fresh user ? Did you do normal sign up and then do the log in ?
> * Did you do login with OAuth and then try to login using normal email and password ?

Hmm, no this was my fault. Seems to work now! Doing some final testing and then will merge! Thanks!

2023-07-31 21:36 UTC, homanp commented
I'm merging this together with #222

2023-07-31 21:36 UTC, closed without merging