Weaviate
homanp/superagent pull request #207
Opened 2023-07-21 16:26 UTC by Elliot-Construct

Added weaviate support, currently untested. 
Suggest creating new branch for this P/R for testing purposes.

2023-07-21 16:35 UTC, homanp commented
@Elliot-Construct this looks amazing, I’ll test it and merge!

2023-07-24 23:03 UTC, homanp requested changes
Some small comments @Elliot-Construct

2023-07-24 23:03 UTC, homanp commented on app/lib/vectorstores/weaviate.py
> +            client=weaviate_client
This should include the namespace for filtering as as well. Otherwise it will query all docs in the index (see Pinecone example).

2023-07-24 23:03 UTC, homanp commented on app/lib/vectorstores/supabase.py
> +            texts=docs,
Is there a way to filter using metadata such as the `namespace` in Pinecone and Weaviate?

2023-07-24 23:34 UTC, Elliot-Construct commented on app/lib/vectorstores/weaviate.py
> +            client=weaviate_client
Done this

2023-07-24 23:34 UTC, Elliot-Construct commented on app/lib/vectorstores/supabase.py
> +            texts=docs,
I believe we may be looking for 'Collections' in supabase?
What do you think?

2023-07-24 23:39 UTC, Elliot-Construct commented on app/lib/vectorstores/supabase.py
> +            texts=docs,
Collections and namespaces are generally different concepts:

A namespace (in Pinecone/Weaviate) is a way to segregate or filter vectors stored in the same underlying index. It's an attribute used during query time.
A collection typically refers to a separate index or database table. Storing vectors in different collections means they are in entirely separate indexes/tables.
Supabase is a relational database, so it doesn't have a direct notion of namespaces like Pinecone/Weaviate.

However, Supabase allows filtering by metadata columns during query time. This can function similarly to namespaces - you store a "namespace" column with each vector and filter by it when querying.

So in summary:

Pinecone/Weaviate namespaces: Filtering within the same index
Supabase "namespaces": Filtering by metadata column
Different collections: Entirely separate indexes/tables
Since Supabase doesn't directly support namespaces, using a metadata column to filter results is the closest equivalent.

So it might be wise to implement a namespace column in the metadata in the collection creation process.

2023-07-26 22:32 UTC, homanp requested changes
Can't seem to get this to work properly with weaviate. Would you mind installing and running this tinder if you can fix it? @Elliot-Construct

2023-07-26 22:32 UTC, homanp commented on app/lib/vectorstores/supabase.py
> +    def from_documents(self, docs, embeddings, table_name):
I guess `table_name` is not needed as a parameter since it's defined on line 10 already?

2023-08-10 06:48 UTC, closed without merging