Seperating workflow agents
homanp/superagent pull request #592
Opened 2023-12-18 17:05 UTC by elisalimli

## Summary

Separating agents' answers

2023-12-18 17:05 UTC, shuriken-bytes commented
The changes in this pull request include:
- Refactoring the `invoke` function in `workflows.py` to use `workflowData` instead of `workflow` and `workflowSteps` instead of `callbacks`.
- Adding a new property `sessionId` to the `WorkflowInvoke` model in `request.py`.
- Modifying the `Chat` component in `chat.tsx` to handle multiple steps and display them in an accordion format.
- Adding new components `Accordion`, `AccordionItem`, `AccordionTrigger`, and `AccordionContent` in `accordion.tsx`.
- Adding new dependencies in `package.json` and `package-lock.json` for the `@radix-ui/react-accordion` package.

Overall, the changes seem to improve the readability and functionality of the code. Great job, @elisalimli! 👏🎉

2023-12-18 17:15 UTC, homanp requested changes
@elisalimli added some comments. Also make sure to run `make format` and `make lint` to format your code correctly. You would have caught my comment if you had ran those commands.

2023-12-18 17:21 UTC, homanp requested changes

2023-12-18 17:21 UTC, homanp commented on libs/superagent/app/api/workflows.py
> +    return {"success": True, "data": "output"}
@elisalimli you are not returning output here but a string "output"

2023-12-19 07:13 UTC, homanp approved these changes

2023-12-19 07:14 UTC, merged