Improving docs of running locally page
homanp/superagent pull request #609
Opened 2023-12-23 19:23 UTC by elisalimli

## Summary
This PR solves #589 

- [ ] My code follows the code style of this project and passes `make format`.
- [x] My change requires a change to the documentation.
- [x] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

2023-12-23 19:23 UTC, shuriken-bytes commented
- The `DATABASE_URL` and `DATABASE_MIGRATION_URL` variables in the `.env` file should be updated with the correct host name and port for the Supabase instance.
- The command `supabase start` should be added to start the local Supabase project.
- The command `supabase status` should be added to get the hostname and port of the Supabase instance.
- The database migration steps should be updated to include starting the local Supabase project before running the migrations.
- The `config.toml` file should be updated with the correct port numbers for the API, database, Studio, and other services.

2023-12-23 21:07 UTC, homanp approved these changes

2023-12-23 21:08 UTC, homanp requested changes
Please fix conflicts @elisalimli

2023-12-24 15:38 UTC, homanp approved these changes

2023-12-24 15:38 UTC, merged