Configuring Vector Databases using UI
homanp/superagent pull request #633
Opened 2024-01-02 19:50 UTC by elisalimli

## Summary

Fixes #510 

- [x] My code follows the code style of this project and passes `make format`.
- [ ] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

2024-01-02 19:50 UTC, shuriken-bytes commented
The changes in the pull request include:
- Importing and using new components and libraries.
- Adding a new page for vector databases.
- Adding a new component for configuring vector databases.
- Adding new metadata for vector database providers.
- Adding API methods for managing vector databases.
- Adding new models for vector databases.

Overall, the changes look good and seem to add new functionality for managing vector databases. Great job, @elisalimli! 👍🎉

2024-01-03 08:34 UTC, homanp requested changes
Overall looks good @elisalimli. Some minor changes.

2024-01-03 08:34 UTC, homanp commented on libs/ui/models/models.ts
> +export enum VectorDbProvider {
We have a folder called `types`. Please use this folder instead of creating a new one called models. Otherwise changes look good!

2024-01-03 09:35 UTC, homanp requested changes
@elisalimli I configured Qdrant and tried to upload a datasource. Now getting this error. Seems like it is using Astra which is configured in .env.
```
Total request time: 5.757041931152344 secs
10:33:45.500 | INFO    | prefect.engine - Created flow run 'big-dragon' for flow 'vectorize_datasource'
10:33:45.504 | INFO    | Flow run 'big-dragon' - View at https://app.prefect.cloud/account/f334ed62-d0fa-4ec0-82b5-ca99d40f4ce7/workspace/66ca6af4-03db-48e3-ac39-6b2912281037/flow-runs/flow-run/1b93b3d6-1c85-48f5-bf5a-9feeb0546089
10:33:46.185 | INFO    | Flow run 'big-dragon' - Created task run 'vectorize-0' for task 'vectorize'
10:33:46.187 | INFO    | Flow run 'big-dragon' - Executing 'vectorize-0' immediately...
/Users/ismailpelaseyed/Projects/superagent/.venv/lib/python3.11/site-packages/langchain/document_loaders/pdf.py:169: ResourceWarning: unclosed file <_io.BufferedReader name='/var/folders/rj/mtkv6r8n53l1jyt5y56zmzt00000gn/T/tmpfsmmtiqm/tmp'>
  blob = Blob.from_data(open(self.file_path, "rb").read(), path=self.web_path)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
10:33:46.810 | ERROR   | Task run 'vectorize-0' - Encountered exception during execution:
Traceback (most recent call last):
  File "/Users/ismailpelaseyed/Projects/superagent/.venv/lib/python3.11/site-packages/prefect/engine.py", line 1733, in orchestrate_task_run
    result = await call.aresult()
             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/superagent/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult
    return await asyncio.wrap_future(self.future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/superagent/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 345, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/superagent/libs/superagent/app/datasource/flow.py", line 50, in vectorize
    vector_store = VectorStoreBase(
                   ^^^^^^^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/superagent/libs/superagent/app/vectorstores/base.py", line 33, in __init__
    self.instance = self.get_database()
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/superagent/libs/superagent/app/vectorstores/base.py", line 67, in get_database
    return vectorstore_classes.get(self.vectorstore)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AstraVectorStore.__init__() got an unexpected keyword argument 'index_name'
10:33:47.018 | ERROR   | Task run 'vectorize-0' - Finished in state Failed("Task run encountered an exception TypeError: AstraVectorStore.__init__() got an unexpected keyword argument 'index_name'")
10:33:47.030 | ERROR   | Flow run 'big-dragon' - Encountered exception during execution:
Traceback (most recent call last):
  File "/Users/ismailpelaseyed/Projects/superagent/.venv/lib/python3.11/site-packages/prefect/engine.py", line 829, in orchestrate_flow_run
    result = await flow_call.aresult()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/superagent/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult
    return await asyncio.wrap_future(self.future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/superagent/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 345, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/superagent/libs/superagent/app/datasource/flow.py", line 86, in vectorize_datasource
    await vectorize(
  File "/Users/ismailpelaseyed/Projects/superagent/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/api.py", line 182, in wait_for_call_in_loop_thread
    return call.result()
           ^^^^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/superagent/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 282, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/superagent/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 168, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/ismailpelaseyed/Projects/superagent/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 345, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/superagent/.venv/lib/python3.11/site-packages/prefect/engine.py", line 1312, in get_task_call_return_value
    return await future._result()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/superagent/.venv/lib/python3.11/site-packages/prefect/futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/superagent/.venv/lib/python3.11/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "/Users/ismailpelaseyed/Projects/superagent/.venv/lib/python3.11/site-packages/prefect/engine.py", line 1733, in orchestrate_task_run
    result = await call.aresult()
             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/superagent/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult
    return await asyncio.wrap_future(self.future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/superagent/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 345, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/superagent/libs/superagent/app/datasource/flow.py", line 50, in vectorize
    vector_store = VectorStoreBase(
                   ^^^^^^^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/superagent/libs/superagent/app/vectorstores/base.py", line 33, in __init__
    self.instance = self.get_database()
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/superagent/libs/superagent/app/vectorstores/base.py", line 67, in get_database
    return vectorstore_classes.get(self.vectorstore)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AstraVectorStore.__init__() got an unexpected keyword argument 'index_name'
Total request time: 4.258002758026123 secs
```

2024-01-03 10:11 UTC, elisalimli commented
@homanp fixed.

2024-01-03 11:02 UTC, homanp requested changes
@elisalimli getting the following error now when adding a datasource with Qdrant activated: 

```
  File "/Users/ismailpelaseyed/Projects/superagent/libs/superagent/app/vectorstores/base.py", line 49, in get_database
    self.DEFAULT_INDEX_NAME,
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'VectorStoreBase' object has no attribute 'DEFAULT_INDEX_NAME'
12:01:14.790 | ERROR   | Flow run 'mighty-pillbug' - Finished in state Failed("Flow run encountered an exception. AttributeError: 'VectorStoreBase' object has no attribute 'DEFAULT_INDEX_NAME'")
Total request time: 5.273561954498291 secs
```

2024-01-03 18:22 UTC, homanp approved these changes

2024-01-03 18:22 UTC, merged