AzureOpenAI Fix
homanp/superagent pull request #637
Opened 2024-01-05 10:11 UTC by shubham184

## Summary

1. Create Agents with LLm Provider AzureOpenAI
2. Tools & Datasources were not working with AzureOpenAI > required version update
3. Please check pyproject.toml as there have been version updates.

Fixes

Depends on

## Test plan

-

## Screenshots

## Checklist

- [ x ] My code follows the code style of this project and passes `make format`.
- [ ] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ x ] My change has adequate unit test coverage.

2024-01-05 22:54 UTC, homanp commented
@elisalimli could you review please?

2024-01-07 11:25 UTC, elisalimli requested changes

2024-01-07 11:25 UTC, elisalimli commented on libs/superagent/app/utils/llm.py
> +        "GPT_4_1106_PREVIEW",
These LLM names have to be different.

2024-01-07 11:25 UTC, elisalimli commented on libs/superagent/app/api/agents.py
> +                    break
Since OpenAI and Azure LLM names are the same, this logic will cause an issue.

Let's say you have configured both OpenAI and Azure. If you try to pass llmModel=GPT_3_5_TURBO_16K_0613 this logic will choose OpenAI as provider always.

2024-01-07 11:25 UTC, elisalimli commented on libs/superagent/app/api/agents.py
> +                #break
Please remove this comment.

2024-01-07 11:26 UTC, elisalimli commented on libs/superagent/app/utils/llm.py
> +        "GPT_4_1106_PREVIEW",
Please check out this docs: 

https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models

2024-01-07 23:00 UTC, homanp commented on libs/superagent/app/utils/llm.py
> +        "GPT_4_1106_PREVIEW",
You don't need model name with azure. You need to use the options `deployment`, `apiKey` etc. The current implementation of this should suffice

2024-01-07 23:00 UTC, homanp commented on libs/superagent/app/api/agents.py
> +                    break
This should not be neccessary

2024-01-08 05:32 UTC, elisalimli commented on libs/superagent/app/api/agents.py
> +                    break
> This should not be neccessary

Why? am I missing something?

2024-01-08 06:26 UTC, shubham184 commented on libs/superagent/app/utils/llm.py
> +        "GPT_4_1106_PREVIEW",
The current codebase uses deployment name, so it doesn't matter which models you provide over here. so either we could remove deployment name from the configuration then pass in these models or just pass in the deployment name and remove these models al together.

2024-01-08 06:27 UTC, shubham184 commented on libs/superagent/app/api/agents.py
> +                    break
I need to check what happens when a new Provider is enabled, is the old one deleted or it stays inactive. if it stays inactive the @elisalimli might be correct it will always choose the first one that is linked to the api user

2024-01-08 08:24 UTC, homanp commented on libs/superagent/app/utils/llm.py
> +        "GPT_4_1106_PREVIEW",
> The current codebase uses deployment name, so it doesn't matter which models you provide over here. so either we could remove deployment name from the configuration then pass in these models or just pass in the deployment name and remove these models al together.

Let's keep the current deployment name way of doing this, so I think the above can be removed?

2024-01-09 16:34 UTC, shubham184 commented on libs/superagent/app/api/agents.py
> +                    break
I tried with enabling both azure and openai and it works fine. when you select openai, the ui gives you the option to select model in case of azure  openai you don't get model selection (see attached screenshot)
<img width="973" alt="Screenshot 2024-01-09 at 5 33 42 PM" src="https://github.com/homanp/superagent/assets/38903550/474ad06b-72b7-40fa-bc74-49eff2661258">

<img width="524" alt="Screenshot 2024-01-09 at 5 32 42 PM" src="https://github.com/homanp/superagent/assets/38903550/4185ddb7-f198-48b7-a6f6-59732d11e7ab">
<img width="548" alt="Screenshot 2024-01-09 at 5 32 58 PM" src="https://github.com/homanp/superagent/assets/38903550/f60e8ab6-f8dd-4221-aa2d-962f2879a4c9">

2024-01-09 16:39 UTC, shubham184 commented on libs/superagent/app/api/agents.py
> +                    break
although a new bug, if i configure an llm there's no way to disable or delete it

2024-01-26 05:58 UTC, elisalimli commented
This is fixed by #684. Closing this.

2024-01-26 05:58 UTC, closed without merging