Revamp the vector databases UI
homanp/superagent pull request #668
Opened 2024-01-21 21:53 UTC by homanp

## Summary

This PR revamps the configuration UI for vector databases.

## Checklist

- [x] My code follows the code style of this project and passes `make format`.
- [ ] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

2024-01-22 00:19 UTC, homanp commented
@elisalimli can you review this. I have tested it on my own but would be good if you could review and test this to make sure it works as intended. I copied some of the code you had added.

2024-01-22 12:16 UTC, elisalimli requested changes

2024-01-22 12:16 UTC, elisalimli commented on libs/ui/app/integrations/storage.tsx
> +  }, [])
When one adds a new vector database, we are not managing the state correctly. Even though we run the router.refresh, the  `configuredDBs` array stays the same. The reason is the router.refresh is meant for server components, we need to handle the refetching on client side ourselves. 


Here's one of the possible fixes we may do:

```typescript
 const [isFetchVectorDBs, setIsFetchVectorDBs] = useState(true)

  const { value: configuredDBs, loading } = useAsync(async () => {  
    const { data } = await api.getVectorDbs()
    return data
  }, [isFetchVectorDBs])

 const onSubmit = (...) => { 
   // business logic here
   
   setIsFetchVectorDBs(prev => !prev)
 }

```

2024-01-22 12:16 UTC, elisalimli commented on libs/ui/app/integrations/storage.tsx
> +      {Array(5).fill(<Skeleton className="h-[60px] w-full" />)}
let's specify the key here otherwise react throws an error

2024-01-23 04:55 UTC, homanp commented on libs/ui/app/integrations/storage.tsx
> +  }, [])
I moved the API request to the server instead. No reason to do it in the client really.

2024-01-23 05:29 UTC, merged