Fix Azure
homanp/superagent pull request #684
Opened 2024-01-24 07:50 UTC by elisalimli

## Summary

This PR fixes #666 

- [x] My code follows the code style of this project and passes `make format`.
- [ ] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

2024-01-24 18:53 UTC, homanp approved these changes

2024-01-24 21:35 UTC, homanp requested changes
Please remove comments from the code @elisalimli otherwise looks ok

2024-01-24 22:07 UTC, homanp requested changes

2024-01-24 22:07 UTC, homanp commented on libs/superagent/app/api/agents.py
I'm doing a POST request to the create agent api with my account, 
<img width="486" alt="Screenshot 2024-01-24 at 14 06 45" src="https://github.com/homanp/superagent/assets/2464556/2bbf3da1-9103-4160-af9b-3050e6049de3">

This seems to be broken, imo. Did you test this @elisalimli

2024-01-25 07:09 UTC, elisalimli commented
@homanp This should work now, thanks for the catch!

2024-01-25 23:45 UTC, homanp approved these changes

2024-01-25 23:47 UTC, merged