Workflow Config YAML Parser
homanp/superagent pull request #709
Opened 2024-01-28 20:27 UTC by elisalimli

## Summary

- [ ] add unit tests

Fixes #688 

## Checklist

- [x] My code follows the code style of this project and passes `./lint-and-format.sh format`.
- [x] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

2024-01-29 08:53 UTC, homanp requested changes
@elisalimli please try this config instead, it would remove the need to create two extra tables:

```
model Workflow {
  id            String            @id @default(uuid())
  name          String
  description   String?
  createdAt     DateTime          @default(now())
  updatedAt     DateTime          @updatedAt
  steps         WorkflowStep[]
  apiUserId     String
  apiUser       ApiUser           @relation(fields: [apiUserId], references: [id])
  workflowConfigs WorkflowConfig[]
}

model WorkflowConfig {
  id            String    @id @default(uuid())
  configYaml    String    @db.Text
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt
  workflowId    String
  workflow      Workflow  @relation(fields: [workflowId], references: [id], onDelete: Cascade)

  @@unique([workflowId, createdAt])
}
```

Then you can build the API like this: 
POST: `/workflows/workflowId/config`

```
 config = await client.workflow_config.create({
        'config_yaml': config_yaml,
        'workflow': {
            'connect': {'id': workflow_id}
        }
    })
```

Get a config:
GET: `/worflows/worflowId/config/configId`

```
config = await client.workflow_config.find_first({
        'where': {
            'workflow_id': workflow_id,
            'id': config_id
        }
    })
```
Get all worflows: 
GET: `/workflows/workflowId/config`

```
configs = await client.workflow_config.find_many({
        'where': {
            'workflow_id': workflow_id
        },
        'order_by': {
            'created_at': 'desc'
        }
    })
```

2024-01-29 15:29 UTC, elisalimli commented
@homanp 

why do we need the last part?
```
  @@unique([workflowId, createdAt])
```

2024-01-30 02:59 UTC, homanp requested changes

2024-01-30 02:59 UTC, homanp commented on libs/superagent/prisma/schema.prisma
> +  WorkflowConfig WorkflowConfig[]
Change this to workflowConfig and stick to naming conventions.

2024-01-30 02:59 UTC, homanp commented on libs/superagent/app/api/agents.py
> +                **body.dict(exclude_unset=True),
What does this do compared to the previous line?

2024-01-30 02:59 UTC, homanp commented on libs/superagent/app/utils/helpers.py
Can this handle nested assistants. E.g agent as a tool? this case is special because the syntax will have to look something like this:

```
- superagent:
  ...config
  tools:
    - superagent:
      ...config
```

2024-01-30 07:03 UTC, elisalimli commented on libs/superagent/app/api/agents.py
> +                **body.dict(exclude_unset=True),
if some parameters is None this excludes them.

https://stackoverflow.com/questions/73198957/how-to-exclude-optional-unset-values-from-a-pydantic-model-using-fastapi

2024-01-30 07:05 UTC, elisalimli commented on libs/superagent/app/utils/helpers.py
Not now, but we can add a check if tool type is in the TOOL_TYPE_MAPPING, treat it as a tool otherwise assistant

2024-01-30 07:06 UTC, homanp commented on libs/superagent/app/utils/helpers.py
I will create a separate issue for that. Let's leave for now.

2024-01-30 08:44 UTC, elisalimli commented on libs/superagent/app/utils/helpers.py
#733

2024-01-30 18:50 UTC, homanp approved these changes
Good work on this!

2024-01-30 18:51 UTC, merged