Azure OpenAI API
homanp/superagent pull request #71
Opened 2023-05-30 11:42 UTC by shubham184

## Summary

Fixes

Depends on

## Test plan

-

## Screenshots

## Types of changes

## Checklist

- [x] My code follows the code style of this project and passes {`style_guide_run_command`}.
- [ ] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate [Unit Test coverage]({TestCoverage}).

2023-05-30 12:52 UTC, homanp requested changes
@shubham184 Big thanks for this PR. I've added some comments to it. Please have a look and afterwards I can merge this in.

2023-05-30 12:52 UTC, homanp commented on app/lib/agents.py
> +                    #openai_api_key="71d7dba9e0254d048eda1f8d5ef369da",
Remove this please!

2023-05-30 12:52 UTC, homanp commented on app/lib/agents.py
> +                    openai_api_base="https://fujitsuesgopenai.openai.azure.com/",
Please use environment variables for this.

2023-05-30 12:52 UTC, homanp commented on app/lib/agents.py
> +                    openai_api_type="azure",
Please use environment variables for this.

2023-05-30 12:52 UTC, homanp commented on app/lib/agents.py
> +                    openai_api_version="2023-03-15-preview",
Please use environment variables for this.

2023-05-30 12:52 UTC, homanp commented on app/lib/agents.py
> +import logging
Does your PR need logging enabled? If not, please remove.

2023-05-31 07:42 UTC, homanp commented
@shubham184 thanks for this contribution, I left some comments for you. As soon as these are resolved I'll run some tests and merge.

2023-06-02 05:25 UTC, shubham184 commented on app/lib/agents.py
> +                    #openai_api_key="71d7dba9e0254d048eda1f8d5ef369da",
done

2023-06-02 05:25 UTC, shubham184 commented on app/lib/agents.py
> +                    openai_api_base="https://fujitsuesgopenai.openai.azure.com/",
done

2023-06-02 05:25 UTC, shubham184 commented on app/lib/agents.py
> +                    openai_api_type="azure",
done

2023-06-02 05:25 UTC, shubham184 commented on app/lib/agents.py
> +                    openai_api_version="2023-03-15-preview",
done

2023-06-02 10:35 UTC, homanp approved these changes
Thanks for making the changes @shubham184 !

2023-06-02 11:43 UTC, shubham184 commented on app/lib/agents.py
> +import logging
removed

2023-06-03 20:52 UTC, homanp commented
@shubham184 could you run `make lint` and `make format`. I have resolved the merge conflicts. After that I can will merge this PR.

2023-06-07 10:58 UTC, merged

2023-06-07 10:59 UTC, homanp commented
@shubham184 did some formatting changes and merge this! Thank you for your contribution!