Add Support for OpenAI Assistants in SAML
homanp/superagent pull request #755
Opened 2024-02-04 19:50 UTC by elisalimli

2024-02-05 17:47 UTC, elisalimli commented on libs/superagent/app/api/agents.py
> +            oai_assistant = await oai.beta.assistants.update(
we are already updating openai assistant above, there's no need for this.

2024-02-06 11:52 UTC, homanp requested changes
``` 
    async for chunk in self.body_iterator:
  File "/Users/ismailpelaseyed/Projects/superagent/libs/superagent/app/api/workflows.py", line 279, in send_message
    track_agent_invocation(
  File "/Users/ismailpelaseyed/Projects/superagent/libs/superagent/app/utils/analytics.py", line 43, in track_agent_invocation
    "llm_model": data.get("agent", {}).get("llmModel", None),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Agent' object has no attribute 'get'
```
Getting this when a invoke a workflow that is created. Just press New Workflow and you will see it.

2024-02-06 15:05 UTC, homanp requested changes
@elisalimli two things:

1. Stop streaming OpenAI assistnat
2. Updating workflows breaks the workflow steps as per our call
3. The agent chat comment I just added to the PR. Fails on build:
```
Type error: Type '{ type: string; message: string; isSuccess?: boolean \| undefined; key: number; traceId: string; profile: Profile; }' is not assignable to type 'IntrinsicAttributes & MessageProps'.
--
15:59:30.580 | Property 'traceId' does not exist on type 'IntrinsicAttributes & MessageProps'.
15:59:30.580 |  
15:59:30.580 | 214 \|                 <Message
15:59:30.580 | 215 \|                   key={index}
15:59:30.580 | > 216 \|                   traceId={session ? `${agent.id}-${session}` : agent.id}
15:59:30.580 | \|                   ^
15:59:30.580 | 217 \|                   profile={profile}
15:59:30.580 | 218 \|                   {...message}
15:59:30.580 | 219 \|                 />
15:59:30.881 | Error: Command "npm run build" exited with 1
```

2024-02-06 15:05 UTC, homanp commented on libs/ui/app/agents/[agentId]/chat.tsx
> +                  traceId={session ? `${agent.id}-${session}` : agent.id}
This throws an error in build error:

```

Type error: Type '{ type: string; message: string; isSuccess?: boolean \| undefined; key: number; traceId: string; profile: Profile; }' is not assignable to type 'IntrinsicAttributes & MessageProps'.
--
15:59:30.580 | Property 'traceId' does not exist on type 'IntrinsicAttributes & MessageProps'.
15:59:30.580 |  
15:59:30.580 | 214 \|                 <Message
15:59:30.580 | 215 \|                   key={index}
15:59:30.580 | > 216 \|                   traceId={session ? `${agent.id}-${session}` : agent.id}
15:59:30.580 | \|                   ^
15:59:30.580 | 217 \|                   profile={profile}
15:59:30.580 | 218 \|                   {...message}
15:59:30.580 | 219 \|                 />
15:59:30.881 | Error: Command "npm run build" exited with 1
```

2024-02-06 17:46 UTC, merged