Adding Support for Super RAG in SAML
homanp/superagent pull request #829
Opened 2024-02-15 21:52 UTC by elisalimli

2024-02-16 08:17 UTC, elisalimli commented
@homanp what's the purpose of this code? why not just use json.loads function?

https://github.com/homanp/superagent/blob/05333bdab47587f3e309d180d1e6b56eee7589c5/libs/superagent/app/agents/langchain.py#L46-L56

2024-02-16 08:21 UTC, homanp commented
> @homanp what's the purpose of this code? why not just use json.loads function?
> 
> 
> 
> https://github.com/homanp/superagent/blob/05333bdab47587f3e309d180d1e6b56eee7589c5/libs/superagent/app/agents/langchain.py#L46-L56

It creates Pydantic from json I think. Let this be for now.

2024-02-17 22:26 UTC, homanp requested changes
Updating the superrag in the yaml throws error. In this case I removed superrag and added it back multiple times making it throw error:

```
ERROR:  'NoneType' object has no attribute 'metadata'
Traceback (most recent call last):
  File "/Users/ismailpelaseyed/Projects/superagent/libs/superagent/app/api/workflow_configs/workflow_configs.py", line 50, in add_config
    await processor.process_assistants(old_config, new_config)
  File "/Users/ismailpelaseyed/Projects/superagent/libs/superagent/app/api/workflow_configs/processors/agent_processor.py", line 141, in process_assistants
    await self.process_assistant(
  File "/Users/ismailpelaseyed/Projects/superagent/libs/superagent/app/api/workflow_configs/processors/agent_processor.py", line 109, in process_assistant
    await new_superrag_processor.process(
  File "/Users/ismailpelaseyed/Projects/superagent/libs/superagent/app/api/workflow_configs/processors/superagent.py", line 54, in process
    await datasource_manager.delete_datasource(
  File "/Users/ismailpelaseyed/Projects/superagent/libs/superagent/app/api/workflow_configs/api/api_datasource_superrag_manager.py", line 121, in delete_datasource
    tool_metadata = json.loads(tool.metadata)
                               ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'metadata'
Total request time: 1.4729390144348145 secs
```

2. The API from Super-Rag return `422 Unprocessable Entity`. 

3. I will remove the possiblity to set encoder. We will use a pre-defined one for this.

2024-02-17 23:38 UTC, homanp requested changes

2024-02-17 23:38 UTC, homanp commented on libs/superagent/app/api/workflow_configs/saml_schema.py
> +    encoder: Optional[str]  # for superrag
This shouldn't be necessary since I've added a default encoder.

2024-02-17 23:38 UTC, homanp commented on libs/superagent/app/api/workflow_configs/saml_schema.py
> +    database_provider: Optional[str]  # for superrag
This should be set automatically by superagent. if you do not have a vector db connected this should throw an error.

2024-02-18 08:08 UTC, elisalimli commented on libs/superagent/app/api/workflow_configs/saml_schema.py
> +    database_provider: Optional[str]  # for superrag
yeah, but if a one have configured multiple databases, how we can know which one they want to choose?

2024-02-18 17:45 UTC, homanp commented on libs/superagent/app/api/workflow_configs/saml_schema.py
> +    database_provider: Optional[str]  # for superrag
Ok, we can leave it in.

2024-02-19 19:29 UTC, homanp requested changes
Regular tool usage seems to be broken: 

```yaml
workflows:
  - superagent:
      llm: gpt-4-1106-preview
      name: Earnings assistant
      intro: 👋 Hi there! How can I help you?
      tools:
        - browser:
            name: browser
            use_for: searching the internet.
      prompt: Use the earnings report to answer any questions
```

<img width="1271" alt="Screenshot 2024-02-19 at 11 28 51" src="https://github.com/homanp/superagent/assets/2464556/77c1a4f0-0cb7-45f3-89fd-dd7c11f4aec9">

2024-02-19 20:03 UTC, homanp approved these changes

2024-02-19 20:03 UTC, merged